### ISSUE TITLE
tallest buildings data

### ISSUE THREAD

**Issue by Mosquid** [Mosquid/gazillion#4]
we are looking for a contributor willing to help us with a JSON file, containing a list of the top 50 tallest buildings

**Comment by saptarsi96** [comment]
Hi, @Mosquid I would like to work on this. Can you please provide the JSON file?

**Comment by Mosquid** [comment]
@saptarsi96 [here you go](https://github.com/Mosquid/gazillion/blob/master/building.json). Please note: we do not provide contributors with Hacktoberfest t-shirts. But your name will be listed in our contributors list

**Comment by saptarsi96** [comment]
@Mosquid Can you please review this PR?

- [X] Completed Tallest 100 Buildings Data
- [X] JSON proper formatting 
- [x]  Waiting for review

**Comment by Mosquid** [comment]
@saptarsi96 well done
